databases:
  - name: tweetscanner
    databaseName: tweetscanner
    user: tweetscanner

services:
  - type: web
    name: tweetscanner
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn tweetscanner.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tweetscanner
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
  - type: worker
    name: queue
    region: ohio
    env: python
    buildCommand: "poetry install"
    startCommand: "celery --app tasks worker --loglevel info --concurrency 4"
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
