databases:
  - name: tweetscanner
    databaseName: tweetscanner
    user: tweetscanner

services:
  - type: web
    name: tweetscanner
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn tweetscanner.wsgi:application --timeout 90"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tweetscanner
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
