default_context:
  project_name: 'twitter-scan'
  project_slug: 'twitter-scan'
  domain_main: 'scanmytweets.com'
  domain_staging: 'stag.scanmytweets.com'
  docker_swarm_stack_name_main: 'scanmytweets-com'
  docker_swarm_stack_name_staging: 'stag-scanmytweets-com'
  secret_key: '0y_zd5gf3mcp=u0sez$l44)8q^!u-$u0_9ylj92*af$v'
  first_superuser: 'admin@scanmytweets.com'
  first_superuser_password: 'fxd9GzTuomJcxx%L!yo2'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.scanmytweets.com", "https://stag.scanmytweets.com", "https://scanmytweets.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: 'admin'
  smtp_password: 'YjP3tZt@@^%gW!P1T*bH'
  smtp_emails_from_email: 'info@scanmytweets.com'
  postgres_password: 'uKI24Twr2@4GQIp44f#u'
  pgadmin_default_user: 'admin@scanmytweets.com'
  pgadmin_default_user_password: '!2u2gzLX9MFzIdEAqOWD'
  traefik_constraint_tag: 'scanmytweets.com'
  traefik_constraint_tag_staging: 'stag.scanmytweets.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'fxd9GzTuomJcxx%L!yo2'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
