"""Add column last_name to User model

Revision ID: 04f0a83a95be
Revises: c242645ce722
Create Date: 2021-03-26 02:03:05.863670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "04f0a83a95be"
down_revision = "c242645ce722"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
