"""Add column last_name to User model

Revision ID: 48170e59972a
Revises: 04f0a83a95be
Create Date: 2021-05-29 12:30:24.997523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48170e59972a'
down_revision = '04f0a83a95be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
