"""created twitter username model

Revision ID: 88f064fd64ac
Revises: 48170e59972a
Create Date: 2021-05-29 21:52:13.093558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f064fd64ac'
down_revision = '48170e59972a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('username', sa.String(), nullable=False))
    op.create_index(op.f('ix_item_username'), 'item', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_username'), table_name='item')
    op.drop_column('item', 'username')
    # ### end Alembic commands ###
