"""Add column last_name to User model

Revision ID: c242645ce722
Revises: 7ebf736114be
Create Date: 2021-03-26 01:59:04.467478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c242645ce722'
down_revision = '7ebf736114be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
