# Generated by Django 3.2.13 on 2022-07-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_twitterusersearched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterusersearched',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='twitterusersearched',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
    ]
